# Generated by Django 3.2.4 on 2021-08-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='guest_can_pause',
        ),
    ]
